### ISSUE TITLE
no results in your soup.find_all (except layover)

### ISSUE THREAD

**Issue by erstert3st** [Pechoa1/Kayak-Webscrape#1]
Hey nice project
I am getting no results in your soup.find_all (except layover)
Is it working on your pc ? may i should switch to Windows 
thanks btw

**Comment by Pechoa1** [comment]
Hello,

I am still working on this project, I think the problem you are receiving is from when Kayak loads a dynamic page meaning the variable names change. When the code runs if you receive "ran dynamic" in the console, all the data points will not be gathered. This is happening since the HTML structure for the webpage is different. I am still working on a solution for this issue. Try the program and if it does not work when the console prints "ran static" let me know and I will look into it further.

Hope this helps

**Comment by Pechoa1** [comment]
Hello,

It seems some of the page structure has been changed. The static page does not seem to exist anymore, thus I will need to revise this. It seems the load_more function will need to be adjusted, along with most of the soup.find_all. 

Thank you for bringing this to my attention, I will start working on a solution.
